import 'package:equatable/equatable.dart';
import 'package:local_lending_app/domain/entities/repayment_frequency.dart';
import 'package:local_lending_app/domain/entities/repayment_installment.dart';

/// The complete repayment plan for a loan, generated by [EmiCalculator].
class RepaymentSchedule extends Equatable {
  const RepaymentSchedule({
    required this.principalRupees,
    required this.annualInterestRatePercent,
    required this.frequency,
    required this.tenure,
    required this.disbursementDate,
    required this.installmentAmountRupees,
    required this.totalRepayableRupees,
    required this.totalInterestRupees,
    required this.installments,
  });

  /// Original loan principal in ₹.
  final double principalRupees;

  /// Flat annual interest rate applied.
  final double annualInterestRatePercent;

  /// Repayment frequency.
  final RepaymentFrequency frequency;

  /// Tenure in the frequency's natural unit (days/weeks/fortnights/months).
  final int tenure;

  /// Date the loan was disbursed.
  final DateTime disbursementDate;

  /// Standard installment amount in ₹ (last installment may differ by rounding).
  final double installmentAmountRupees;

  /// Total amount to be repaid (principal + interest) in ₹.
  final double totalRepayableRupees;

  /// Total interest cost in ₹.
  final double totalInterestRupees;

  /// Ordered list of installments (index 0 = first due).
  final List<RepaymentInstallment> installments;

  @override
  List<Object?> get props => [
    principalRupees,
    annualInterestRatePercent,
    frequency,
    tenure,
    disbursementDate,
    installmentAmountRupees,
    totalRepayableRupees,
    totalInterestRupees,
    installments,
  ];

  // ---------------------------------------------------------------------------
  // Computed properties
  // ---------------------------------------------------------------------------

  /// Number of installments that have been fully paid.
  int get paidCount =>
      installments.where((i) => i.status == InstallmentStatus.paid).length;

  /// Number of installments that are overdue.
  int get overdueCount =>
      installments.where((i) => i.status == InstallmentStatus.overdue).length;

  /// Total amount paid so far across all installments in ₹.
  double get totalPaidRupees =>
      installments.fold(0, (sum, i) => sum + i.paidAmountRupees);

  /// Outstanding balance (total repayable minus total paid) in ₹.
  double get outstandingRupees => totalRepayableRupees - totalPaidRupees;

  /// Progress as a fraction (0.0 – 1.0).
  double get progress =>
      installments.isEmpty ? 0 : paidCount / installments.length;

  /// The next unpaid installment, or null if all are paid.
  RepaymentInstallment? get nextDue {
    for (final installment in installments) {
      if (installment.status == InstallmentStatus.upcoming ||
          installment.status == InstallmentStatus.partial) {
        return installment;
      }
    }
    return null;
  }

  /// Whether the loan is fully repaid.
  bool get isCompleted => paidCount == installments.length;
}
